/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrmTristone;

import Model.EmployeesModel;
import java.awt.Color;
import java.awt.event.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.Scanner;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;



/**
 *
 * @author Ulises
 */
public class frmEmployee extends javax.swing.JFrame {

    /**
     * Creates new form frmEmployee
     */
    
    
    public frmEmployee()  {
        initComponents();
        
        getContentPane().setBackground(Color.DARK_GRAY);
         //this.setUndecorated(true);
        jtxtMessage.setEditable(false);
        jbtnSendEmployee.setVisible(false);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            //jLabel2.setBackground(Color.white);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtEmployeeNumber = new javax.swing.JTextField();
        jbtnSendEmployee = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        jtxtMessage = new javax.swing.JTextField();
        jlblSettings = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 0));
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(682, 334));

        jtxtEmployeeNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtEmployeeNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtEmployeeNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtEmployeeNumberKeyPressed(evt);
            }
        });

        jbtnSendEmployee.setText("Submint");
        jbtnSendEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSendEmployeeActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tristone.png"))); // NOI18N

        label1.setText("label1");

        label2.setText("label2");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Employee Number");

        jtxtMessage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtxtMessage.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlblSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Setting.png"))); // NOI18N
        jlblSettings.setName("jlblEmployee"); // NOI18N
        jlblSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblSettingsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSendEmployee, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtEmployeeNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
            .addComponent(jtxtMessage)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlblSettings)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(jlblSettings)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnSendEmployee)
                        .addGap(72, 72, 72)))
                .addComponent(jtxtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jbtnSendEmployee.getAccessibleContext().setAccessibleName("btnSubmint");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSendEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSendEmployeeActionPerformed
        // TODO add your handling code here:        
               
            
//       jtxtMessage.setText("Success");
//        jtxtMessage.setBackground(Color.green);                
//        jtxtMessage.setEditable(false);
//                GetSuccess(); 
        //if(formateador.format(ahora).compareTo("8:00")>1)
           // JOptionPane.showConfirmDialog(null,""+formateador.format(ahora));
       //System.out.println (new File (".").getAbsolutePath ());
       //JOptionPane.showConfirmDialog(null,""+formateador.format(ahora));
        // ExistEmployee();       
    }//GEN-LAST:event_jbtnSendEmployeeActionPerformed
    
  private void ReseteBox(){
       Timer timer;
       TimerTask task;
       int time=2000;
       task = new TimerTask() {
           @Override
           public void run() {
               jtxtMessage.setText("");
                jtxtMessage.setBackground(Color.white);                
                jtxtMessage.setEditable(false);
                jtxtEmployeeNumber.setText("");
           }
       };
       
       timer =new Timer();
       timer.schedule(task, time);
       
   }
    
    
    
    private void jtxtEmployeeNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEmployeeNumberKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER )
            ExistEmployee();
    }//GEN-LAST:event_jtxtEmployeeNumberKeyPressed

    private void jlblSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblSettingsMouseClicked
        // TODO add your handling code here:
        //String innerPassword = JOptionPane.showInputDialog(null,"Set Password",);
        String innerPassword="";
        JPasswordField passwordField = new JPasswordField();
        passwordField.setEchoChar('*');
        Object[] obj = {"Please enter the password:\n\n", passwordField};
        Object stringArray[] = {"OK","Cancel"};
        if (JOptionPane.showOptionDialog(null, obj, "Need password",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, stringArray, obj) == JOptionPane.YES_OPTION)
        innerPassword = new String(passwordField.getPassword());
        
        
        if(GetInnerPassword(innerPassword)){
            frmSettings _frmSettings = new frmSettings();
            //_frmScanProduct._idEmployee=  Integer.parseInt(jtxtEmployeeNumber.getText());
            
            _frmSettings.setVisible(true);
            this.dispose();
        }
        else{
                //jtxtMessage.setVisible(true);
                jtxtMessage.setText("Invalid Password");
                jtxtMessage.setBackground(Color.red);                
                jtxtMessage.setEditable(false);
                ReseteBox();
            }
            
    }//GEN-LAST:event_jlblSettingsMouseClicked

    
     private boolean GetInnerPassword(String innerPassword ){
        boolean result = false;
        
        BufferedReader br = null;
        try
        {
           
            String dbPath="";
            String dbName = "";
            String userDB="";
            String passDB="";
            String station="";
            String passApp="";
            String scanSleep="";
            String company="";
            //String serialPort="";
            //String subStation="";
            
            BufferedWriter bw;
            String path=new File ("TristonePath.txt").getAbsolutePath ();
                      
            File file = new File(path);
            if(file.exists())
            {
                Scanner sc = new Scanner(file); 

                dbPath = sc.nextLine();
                dbName = sc.nextLine();
                userDB = sc.nextLine();
                passDB = sc.nextLine();
                station = sc.nextLine();
                //subStation = sc.nextLine();
                company = sc.nextLine();
                passApp = sc.nextLine();                
                scanSleep = sc.nextLine();
                
                //serialPort = sc.nextLine();
            }else{
                bw = new BufferedWriter(new FileWriter(file));
                bw.write(".");
                bw.write(".");
                bw.write(".");
                bw.write(".");
                bw.write(".");
                bw.write(".");
                result= true;
            } 
                 
            
            if(innerPassword.equals(passApp))
                result = true;          
                
           
        }
        catch (Exception ex) {
          ex.printStackTrace();
          return result;
          }
        finally{
            return result;
        }
        
     }
    
    
    private void ExistEmployee(){
        EmployeesModel obj=new EmployeesModel();
        
        if (jtxtEmployeeNumber.getText().isEmpty() ){
            jtxtMessage.setText("Unauthorized User");
            jtxtMessage.setBackground(Color.red);                
            jtxtMessage.setEditable(false);
            ReseteBox();
        }            
        else{
            try{
                boolean result= obj.EmployeeExist(jtxtEmployeeNumber.getText());
                if(result){
                    frmScanProduct _frmScanProduct = new frmScanProduct();
                    //_frmScanProduct._idEmployee=  Integer.parseInt(jtxtEmployeeNumber.getText());
                    _frmScanProduct.getEmployee(jtxtEmployeeNumber.getText());
                    _frmScanProduct.setVisible(true);
                    //this.setVisible(false);                    
                  
                    this.dispose();
                    //JOptionPane.showConfirmDialog(null,"Excelente");
                }
                else{
                    //jtxtMessage.setVisible(true);
                    jtxtMessage.setText("Unauthorized User");
                    jtxtMessage.setBackground(Color.red);
                    jtxtMessage.setEditable(false);
                    ReseteBox();
                }
            }catch(Exception e){
                e.printStackTrace();
                 jtxtMessage.setText(""+ e.getMessage());
                 jtxtMessage.setBackground(Color.red);                
                 jtxtMessage.setEditable(false);
                 ReseteBox();
            }
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmployee().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnSendEmployee;
    private javax.swing.JLabel jlblSettings;
    private javax.swing.JTextField jtxtEmployeeNumber;
    private javax.swing.JTextField jtxtMessage;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
