/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrmTristone;

import Model.EmployeesModel;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.Scanner;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;




/**
 *
 * @author Ulises
 */
public class frmEmployee extends javax.swing.JFrame {

    /**
     * Creates new form frmEmployee
     */
    
    public frmEmployee()  {
        initComponents();

       
        this.setIconImage(new ImageIcon(getClass().getResource("/img/icon_tristone.png")).getImage());
        getContentPane().setBackground(new Color(51,51,51));
         //this.setUndecorated(true);
        jtxtMessage.setEditable(false);
        jbtnSendEmployee.setVisible(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            //jLabel2.setBackground(Color.white);
        jLabel1.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tristone_White.png")).getImage().getScaledInstance(260, 150, Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtEmployeeNumber = new javax.swing.JTextField();
        jbtnSendEmployee = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtMessage = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 0));
        setMaximumSize(null);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtEmployeeNumber.setBackground(new java.awt.Color(51, 51, 51));
        jtxtEmployeeNumber.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jtxtEmployeeNumber.setForeground(new java.awt.Color(255, 255, 255));
        jtxtEmployeeNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtEmployeeNumber.setBorder(null);
        jtxtEmployeeNumber.setOpaque(false);
        jtxtEmployeeNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtEmployeeNumberKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtEmployeeNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 220, 30));

        jbtnSendEmployee.setText("Submint");
        jbtnSendEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSendEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSendEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));
        jbtnSendEmployee.getAccessibleContext().setAccessibleName("btnSubmint");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tristone.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 260, 150));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Employee Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 231, -1));

        jtxtMessage.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jtxtMessage.setForeground(new java.awt.Color(255, 255, 255));
        jtxtMessage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMessage.setBorder(null);
        jtxtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMessageActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 780, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 220, 20));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/automatic_52px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/automatic_50px_colored.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 60, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_barcode_reader.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSendEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSendEmployeeActionPerformed
        // TODO add your handling code here:        
               
            
//       jtxtMessage.setText("Success");
//        jtxtMessage.setBackground(Color.green);                
//        jtxtMessage.setEditable(false);
//                GetSuccess(); 
        //if(formateador.format(ahora).compareTo("8:00")>1)
           // JOptionPane.showConfirmDialog(null,""+formateador.format(ahora));
       //System.out.println (new File (".").getAbsolutePath ());
       //JOptionPane.showConfirmDialog(null,""+formateador.format(ahora));
        // ExistEmployee();       
    }//GEN-LAST:event_jbtnSendEmployeeActionPerformed
    
  private void ReseteBox(){
       Timer timer;
       TimerTask task;
       int time=2000;
       task = new TimerTask() {
           @Override
           public void run() {
               jtxtMessage.setText("");
                jtxtMessage.setBackground(Color.white);                
                jtxtMessage.setEditable(false);
                jtxtEmployeeNumber.setText("");
           }
       };
       
       timer =new Timer();
       timer.schedule(task, time);
       
   }
    
    
    
    private void jtxtEmployeeNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEmployeeNumberKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER )
            ExistEmployee();
    }//GEN-LAST:event_jtxtEmployeeNumberKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //String innerPassword = JOptionPane.showInputDialog(null,"Set Password",);
        String innerPassword="";
        JPasswordField passwordField = new JPasswordField();
        passwordField.setEchoChar('*');
        Object[] obj = {"Please enter the password:\n\n", passwordField};
        Object stringArray[] = {"OK","Cancel"};
        if (JOptionPane.showOptionDialog(null, obj, "Need password",
        JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, stringArray, obj) == JOptionPane.YES_OPTION)
        innerPassword = new String(passwordField.getPassword());
        
        
        if(GetInnerPassword(innerPassword)){
            frmSettings _frmSettings = new frmSettings();
            //_frmScanProduct._idEmployee=  Integer.parseInt(jtxtEmployeeNumber.getText());
            
            _frmSettings.setVisible(true);
            this.dispose();
        }
        else{
                //jtxtMessage.setVisible(true);
                jtxtMessage.setText("Invalid Password");
                jtxtMessage.setBackground(Color.decode("#FF1744"));                
                jtxtMessage.setEditable(false);
                ReseteBox();
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMessageActionPerformed

    
     private boolean GetInnerPassword(String innerPassword ){
        boolean result = false;
        
        BufferedReader br = null;
        try
        {
           
            String dbPath="";
            String dbName = "";
            String userDB="";
            String passDB="";
            String station="";
            String passApp="";
            String scanSleep="";
            String company="";
            //String serialPort="";
            //String subStation="";
            
            BufferedWriter bw;
            String path=new File ("TristonePath.txt").getAbsolutePath ();
                      
            File file = new File(path);
            if(file.exists())
            {
                Scanner sc = new Scanner(file); 

                dbPath = sc.nextLine();
                dbName = sc.nextLine();
                userDB = sc.nextLine();
                passDB = sc.nextLine();
                station = sc.nextLine();
                //subStation = sc.nextLine();
                company = sc.nextLine();
                passApp = sc.nextLine();                
                scanSleep = sc.nextLine();
                
                //serialPort = sc.nextLine();
            }else{
                bw = new BufferedWriter(new FileWriter(file));
                bw.write(".");
                bw.write(".");
                bw.write(".");
                bw.write(".");
                bw.write(".");
                bw.write(".");
                result= true;
            } 
                 
            
            if(innerPassword.equals(passApp))
                result = true;          
                
           
        }
        catch (Exception ex) {
          ex.printStackTrace();
          return result;
          }
        finally{
            return result;
        }
        
     }
    
    
    private void ExistEmployee(){
        EmployeesModel obj=new EmployeesModel();
        
        if (jtxtEmployeeNumber.getText().isEmpty() ){
            jtxtMessage.setText("Unauthorized User");
            jtxtMessage.setBackground(Color.red);                
            jtxtMessage.setEditable(false);
            ReseteBox();
        }            
        else{
            try{
                boolean result= obj.EmployeeExist(jtxtEmployeeNumber.getText());
                if(result){
                    frmScanProduct _frmScanProduct = new frmScanProduct();
                    //_frmScanProduct._idEmployee=  Integer.parseInt(jtxtEmployeeNumber.getText());
                    _frmScanProduct.getEmployee(jtxtEmployeeNumber.getText());
                    _frmScanProduct.setVisible(true);
                    //this.setVisible(false);                    
                  
                    this.dispose();
                    //JOptionPane.showConfirmDialog(null,"Excelente");
                }
                else{
                    //jtxtMessage.setVisible(true);
                    jtxtMessage.setText("Unauthorized User");
                    jtxtMessage.setBackground(Color.red);
                    jtxtMessage.setEditable(false);
                    ReseteBox();
                }
            }catch(Exception e){
                e.printStackTrace();
                 jtxtMessage.setText(""+ e.getMessage());
                 jtxtMessage.setBackground(Color.red);                
                 jtxtMessage.setEditable(false);
                 ReseteBox();
            }
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmployee().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnSendEmployee;
    private javax.swing.JTextField jtxtEmployeeNumber;
    private javax.swing.JTextField jtxtMessage;
    // End of variables declaration//GEN-END:variables
}
