/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrmTristone;

import Entities.EmployeeEntity;
import Entities.ProductsEntity;
import Entities.StationEntity;
import Model.EmployeesModel;
import Model.ProductModel;
import Model.StationModel;
import com.mysql.jdbc.Util;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ulises
 */
public class frmScanProduct extends javax.swing.JFrame {

    
    public String _idEmployee;
    /**
     * Creates new form frmScanProduct
     */
    String dbNameS = "";
    String _cancelCode2="";
    public frmScanProduct() {
        this.setIconImage(new ImageIcon(getClass().getResource("/img/icon_tristone.png")).getImage());
        initComponents();
        getContentPane().setBackground(new Color(51,51,51));
        
        //getEmployee(_idEmployee);
        jtxtMessage.setEditable(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
//        btnestandar.setVisible(false);
//        btnalternativo.setVisible(false);
        jLabel6.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tristone_White.png")).getImage().getScaledInstance(260, 150, Image.SCALE_SMOOTH)));
       
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtNoSAP = new javax.swing.JTextField();
        jlblEmployeeName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlblEmployeeNumb = new javax.swing.JLabel();
        jtxtMessage = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Name:");
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 211, 170, -1));
        jLabel1.getAccessibleContext().setAccessibleName("jlblNameTittle");

        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 199, 239, -1));
        jLabel2.getAccessibleContext().setAccessibleName("jlblName");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 171, -1));
        jLabel3.getAccessibleContext().setAccessibleName("jlblEmployeeNum");

        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 370, 707, -1));
        jLabel4.getAccessibleContext().setAccessibleName("jlblemployeeNumbertxt");

        jtxtNoSAP.setBackground(new java.awt.Color(51, 51, 51));
        jtxtNoSAP.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jtxtNoSAP.setForeground(new java.awt.Color(255, 255, 255));
        jtxtNoSAP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtNoSAP.setBorder(null);
        jtxtNoSAP.setOpaque(false);
        jtxtNoSAP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNoSAPKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtNoSAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 240, -1));
        jtxtNoSAP.getAccessibleContext().setAccessibleName("jtxtSapNumber");

        jlblEmployeeName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jlblEmployeeName.setForeground(new java.awt.Color(255, 255, 255));
        jlblEmployeeName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblEmployeeName.setText("Employee Name:");
        jlblEmployeeName.setName("jlblEmployee"); // NOI18N
        getContentPane().add(jlblEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 400, -1));
        jlblEmployeeName.getAccessibleContext().setAccessibleName("jlblEmployee");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tristone.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 260, 150));

        jlblEmployeeNumb.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jlblEmployeeNumb.setForeground(new java.awt.Color(255, 255, 255));
        jlblEmployeeNumb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblEmployeeNumb.setText("Employee Number:");
        jlblEmployeeNumb.setName("jlblEmployee"); // NOI18N
        getContentPane().add(jlblEmployeeNumb, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 333, 399, -1));

        jtxtMessage.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jtxtMessage.setForeground(new java.awt.Color(255, 255, 255));
        jtxtMessage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jtxtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 800, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SAP Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 246, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 400, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 240, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 275, 400, 10));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_barcode_reader.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNoSAPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNoSAPKeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode() == KeyEvent.VK_ENTER )
        {
      
            String scan = jtxtNoSAP.getText();
            String noSAP;
            String empaque;
            if(scan.endsWith("AC")){
                
            noSAP= scan.substring(0, scan.length() - 2);
            empaque="alternativo";
            
            }else{
                
                 noSAP= scan;
                 empaque="estandar";
            }
            
     
            if(noSAP.equals(_cancelCode2)){
                frmEmployee _frmEmployee=new frmEmployee();
               
                _frmEmployee.setVisible(true);
                this.dispose();
            }
            else if(GetData(noSAP)){
                
                
                boolean result=true;
                ProductsEntity _productEntity=new ProductsEntity();
                StationModel objStationModel =new StationModel();
                ArrayList<Object> listTable=new ArrayList<Object>();
                listTable = objStationModel.GetTableName(dbNameS);
        
                if(listTable.size() > 0){
                    for(Object o : listTable){
                        result= objStationModel.ValidateBartender(o.toString(), noSAP,dbNameS);
                            if(result == true){
                            _productEntity = objStationModel.GetDataProduct(o.toString(), noSAP,dbNameS);

                            frmStandarPAck _frmStandardPack = new frmStandarPAck();
                            _frmStandardPack.SetEmployee(_idEmployee);
                            _frmStandardPack.initialize();
                            _frmStandardPack.SetNoSAP(_productEntity, empaque);
                            _frmStandardPack.setVisible(true);
                            this.dispose();
                        }
                    }
            
                }else
                    {
                        jtxtMessage.setText("Invalid Number");
                        jtxtMessage.setBackground(Color.decode("#FF1744"));                
                        jtxtMessage.setEditable(false);
                        jtxtNoSAP.setText("");
                        ReseteBox();
                    }
                
                
            }else
            {
                jtxtMessage.setText("Invalid Number");
                jtxtMessage.setBackground(Color.decode("#FF1744"));               
                jtxtMessage.setEditable(false);
                jtxtNoSAP.setText("");
                ReseteBox();
            }
        }
            

    }//GEN-LAST:event_jtxtNoSAPKeyPressed
    
    private boolean GetBartender(String dbName,String noSAP){
        boolean result = false;
        boolean result2=false;
         boolean COM = false;
        ProductsEntity _productEntity=new ProductsEntity();
        StationModel objStationModel =new StationModel();
        ArrayList<Object> listTable=new ArrayList<Object>();
        listTable = objStationModel.GetTableName(dbName);
        
        if(listTable.size() > 0){
            for(Object o : listTable){
                result= objStationModel.ValidateBartender(o.toString(), noSAP,dbName);
                
                
                
                if(result == true){
                     
                    //_productEntity = objStationModel.GetDataProduct(o.toString(), noSAP,dbName);
                    //btnalternativo.setVisible(true);
                    //btnestandar.setVisible(true);
                    //jLabel5.setVisible(true);
                    //jLabel8.setVisible(true);
                    //jtxtNoSAP.setEnabled(false);
                    
                                 result2=true;
//                    
//                    try {
//                        if(COM){
////                                frmDigitalScale _frmDigitalScale = new frmDigitalScale();
////                                _frmDigitalScale.SetEmployee(_idEmployee);
////                                _frmDigitalScale.SetNoSAP(_productEntity);
////                                _frmDigitalScale.setVisible(true);
////                                this.dispose();
//                        } else{
////                                frmStandarPAck _frmStandardPack = new frmStandarPAck();
////                                _frmStandardPack.SetEmployee(_idEmployee);
////                                _frmStandardPack.initialize();
////                                _frmStandardPack.SetNoSAP(_productEntity);
////                                _frmStandardPack.setVisible(true);
////                                this.dispose();
//                                  
//                                  
//                        }
//                        
//                        
//                    
//                    } catch (Exception e) {
//                        JOptionPane.showConfirmDialog(null, ""+ e.getMessage(), "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
//                    }finally{
//                        //this.setVisible(false);
//                        //this.dispose();
//                        //break;
//                    }
//                   
                }
            }
        }
        
        return result2;
    }
    
    private void ReseteBox(){
       Timer timer;
       TimerTask task;
       int time=2000;
       task = new TimerTask() {
           @Override
           public void run() {
               jtxtMessage.setText("");
                jtxtMessage.setBackground(Color.white);                
                jtxtMessage.setEditable(false);
           }
       };
       
       timer =new Timer();
       timer.schedule(task, time);
       
   }
    
    private boolean GetData(String noSAP){
        
        boolean result=false;
         String dbPath="";
        String dbName = "";
        String userDB="";
        String passDB="";
        String station="";
        String passApp="";
        String scanSleep="";
        String company="";
        //String serialPort="";
        
        String _cancelCode = "";
        StationEntity _stationEntity = new StationEntity();
        StationModel objStationModel =new StationModel();
        String path=new File ("TristonePath.txt").getAbsolutePath ();
                      
        File file = new File(path);
        try{
                if(file.exists())
                {
                    Scanner sc = new Scanner(file); 

                    dbPath = sc.nextLine();
                    dbName = sc.nextLine();
                    userDB = sc.nextLine();
                    passDB = sc.nextLine();
                    station = sc.nextLine();
                    company = sc.nextLine();
                    passApp = sc.nextLine();
                    scanSleep = sc.nextLine();
                    
                    //serialPort = sc.nextLine();
                    
                    
                    _stationEntity = objStationModel.getStationConf(station);
                    result=GetBartender(_stationEntity.getMysql_db() ,noSAP);
                    dbNameS=_stationEntity.getMysql_db();
                    //_cancelCode2 = _stationEntity.getCancelacion();
                }
                else{
                    jtxtMessage.setText("The File doesn't exist"); 
                    jtxtMessage.setBackground(Color.red);
                    jtxtMessage.setEditable(false);
                    ReseteBox();
                }
                
        }
        catch (Exception e) {
            e.printStackTrace();
            return result;
        }
        finally{
            return result;    
        }
    }
    
    private boolean ExistNoSAP(String noSAP){
        boolean _existNoSAP = false;
        ProductModel objProductModel =new ProductModel();
        _existNoSAP = objProductModel.ProductExist(noSAP);
        if(_existNoSAP)
            _existNoSAP = GetData(noSAP);
        return _existNoSAP;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmScanProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmScanProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmScanProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmScanProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmScanProduct().setVisible(true);                
            }
            
        });
    }
    
    public void getEmployee(String idEmployee)
    {
        EmployeesModel objEmployee=new EmployeesModel();
        EmployeeEntity _employeeEntity=new EmployeeEntity();
        _employeeEntity = objEmployee.getEmployee(idEmployee);
                
        jlblEmployeeName.setText(_employeeEntity.getNameEmployee());
        jlblEmployeeNumb.setText(_employeeEntity.getNumEmployee());
        _idEmployee = _employeeEntity.getIdEmployee();
        
        _cancelCode2=CancelCode();
    }
    
    
        private String CancelCode(){
        String dbPath="";
        String dbName = "";
        String userDB="";
        String passDB="";
        String station="";
        String passApp="";
        String scanSleep="";
        String company="";
        //String serialPort="";
        
        String _cancelCode = "";
        
        StationEntity _stationEntity = new StationEntity();
        StationModel objStationModel =new StationModel();
        
        String path=new File ("TristonePath.txt").getAbsolutePath ();
                      
        File file = new File(path);
        try{
                if(file.exists())
                {
                    Scanner sc = new Scanner(file); 

                    dbPath = sc.nextLine();
                    dbName = sc.nextLine();
                    userDB = sc.nextLine();
                    passDB = sc.nextLine();
                    station = sc.nextLine();
                    company = sc.nextLine();
                    passApp = sc.nextLine();
                    scanSleep = sc.nextLine();
                    
                    //serialPort = sc.nextLine();
              
                    _stationEntity = objStationModel.getStationConf(station);
                    
                    _cancelCode2 = _stationEntity.getCancelacion();
                    
                }
                else{
                    jtxtMessage.setText("The File doesn't exist"); 
                    jtxtMessage.setBackground(Color.red);
                    jtxtMessage.setEditable(false);
                }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        finally{
            return _cancelCode2;
        }
    }
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jlblEmployeeName;
    private javax.swing.JLabel jlblEmployeeNumb;
    private javax.swing.JTextField jtxtMessage;
    private javax.swing.JTextField jtxtNoSAP;
    // End of variables declaration//GEN-END:variables
}
